Dev populate
dekoza/mtgpl pull request #1
Opened 2017-04-28 14:51 UTC by a-trawka

*still in progress*

2017-04-29 12:58 UTC, a-trawka commented
I can see where I've made a mistake: instead of moving populate.py into management/commands/, I've cut the content of it and pasted into newly created file...

2017-05-04 13:00 UTC, dekoza requested changes
Kilka sugestii masz w komentarzach do kodu.

2017-05-04 13:00 UTC, dekoza commented on mtgpl/apps/mtgdb/management/commands/populate.py
> +        if exp is not None:
lepszym testem w tym przypadku jest po prostu `if exp:` - `None` oraz np. pusty napis są "fałszywne". Testy w rodzaju `if exp is not None:` ma najwięcej sensu, gdy np. pusty napis (lub inna "fałszywna" wartość) jest akceptowalny.

2017-05-04 13:00 UTC, dekoza commented on mtgpl/apps/mtgdb/management/commands/populate.py
> +                self.stdout.write(f'{exp} is not an expansion.')
Pamiętaj, że taka składnia działa tylko w Py3.6+

Ponieważ jednak Py3.6+ jest docelowym językiem - jest OK.

2017-05-04 13:00 UTC, dekoza commented on mtgpl/apps/mtgdb/management/commands/populate.py
> +            for subtp in data.get('subtypes', []):
przypomniałem sobie, dlaczego to było poza `if new_card:` - czasami karta może dostać aktualizację podtypów :smiley:

2017-05-04 13:00 UTC, dekoza commented on mtgpl/apps/mtglang/models.py
> +        return self.text
tutaj ewidentnie chodziło mi o zwracanie tłumaczenia, tak samo poniżej

2017-05-04 13:05 UTC, a-trawka commented on mtgpl/apps/mtgdb/management/commands/populate.py
> +                self.stdout.write(f'{exp} is not an expansion.')
Jestem tego świadomy

2017-05-04 13:06 UTC, closed without merging